### PR TITLE
fix: add [COPY] suffix to duplicated tests

### PR DESCRIPTION
**Pull request by joyce-shi**
## Notion ticket link

[Add copy to duplicate title](https://www.notion.so/uwblueprintexecs/Add-copy-to-duplicate-title-5e7db10789c74f458bd7955d523382a7?pvs=4)

## Implementation description
* Add [COPY] suffix to duplicated tests for user clarity

## What should reviewers focus on?
* works as expected
* no breaking changes

### CODE REVIEW

**Review by jfdoming — APPROVED** [review]
Out of curiosity why not do this on the frontend?

**Comment by joyce-shi** [comment]
> 

Adding the suffix or the duplication itself?

**Comment by jfdoming** [comment]
Just the suffix

**Comment by joyce-shi** [comment]
> Just the suffix

resolved via slack

**Pull request merged**
